- name: add apt key
  apt_key:
    url: https://packagecloud.io/gpg.key

- name: add apt repository
  apt_repository:
    repo: deb https://packagecloud.io/grafana/stable/debian wheezy main
    update_cache: yes

- name: install grafana
  apt:
    pkg: grafana
    state: present

- name: configure grafana
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    group: grafana
    mode: 0640
  notify:
    - restart grafana

- meta: flush_handlers

- name: ensure grafana enabled and started
  service:
    name: grafana-server
    enabled: yes
    state: started
