- name: add apt key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key

- name: add apt repository
  apt_repository:
    repo: deb https://repos.influxdata.com/ubuntu trusty stable
    update_cache: yes
